# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

#theme: minimal
day_night: true
font: native
font_size: L
theme_day: minimal
theme_night: minimal

# SEO

site_type: Organization
local_business_type: ''
org_name: 'Puritz Lab of Marine Evolutionary Ecology'
description: The Puritz Lab of Marine Evolutionary Ecology is located with the College of Environmental and Life Sciences at the University of Rhode Island. Our research investigates how natural and anthropogenic processes affect the evolution of marine populations through the lens of larval dispersal. We combine laboratory multi-stressor larval exposure experiments with genomic surveys of natural populations, analyzing patterns of selection and migration in a geographic context using landscape (or seascape) genomic models. Our lab also develops laboratory and bioinformatic methods to facilitate the use of next-generation sequencing in non-model species.
twitter: 'https://x.com/MarineEvoEcoLab'

# Contact (edit or remove options as required)

email: jpuritz@uri.edu
phone: 401-874-9020
address:
  street: 120 Flagg RD
  city: Kingston
  region: RI
  postcode: '02881'
  country: United States
  country_code: US
coordinates:
  latitude: '41.49044'
  longitude: '-71.528328'
directions: 
office_hours:
appointment_url: 
contact_links:
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: false
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
math: false
diagram: false
privacy_pack: false
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
