# Theme metadata
name = "custom_dark"

[light]
  # Primary
  primary = "011D32"

  # Menu
  menu_primary = "#fff"
  menu_text = "#34495e"
  menu_text_active = "#2962ff"
  menu_title = "#2b2b2b"

  # Home sections
  home_section_odd = "#838383"
  home_section_even = "#5E9CCB"

[dark]
  # Primary
  #primary = "#bbdefb"
  primary = "000D18"
  
  link = "#bbdefb"
  link_hover = "#bbdefb"
